# -*- coding: utf-8 -*-
"""19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JNM2uMhZ80Ej4-W0DSmeGiJzJieEJwrv

**1.Write a program to enter name and display as “Hello, Name”.**
"""

name = input("Enter your name: ")
print("Hello,", name)

"""**2. Write a menu driven program to enter two numbers and print the arithmetic operations like
a. + , b. – c.  * . d. / , e. // , f. %**
"""

# Input two numbers
a = float(input("Enter first number: "))
b = float(input("Enter second number: "))

while True:
    print("\n--- MENU ---")
    print("1. Addition (+)")
    print("2. Subtraction (-)")
    print("3. Multiplication (*)")
    print("4. Division (/)")
    print("5. Floor Division (//)")
    print("6. Modulus (%)")
    print("7. Exit")

    choice = int(input("Enter your choice (1-7): "))

    if choice == 1:
        print("Result:", a + b)
    elif choice == 2:
        print("Result:", a - b)
    elif choice == 3:
        print("Result:", a * b)
    elif choice == 4:
        if b != 0:
            print("Result:", a / b)
        else:
            print("Error! Division by zero")
    elif choice == 5:
        if b != 0:
            print("Result:", a // b)
        else:
            print("Error! Division by zero")
    elif choice == 6:
        if b != 0:
            print("Result:", a % b)
        else:
            print("Error! Division by zero")
    elif choice == 7:
        print("Exiting program...")
        break
    else:
        print("Invalid choice! Try again.")

"""**3. Write a program to compute the roots of a quadratic equation.**"""

import math

# Input coefficients
a = float(input("Enter value of a: "))
b = float(input("Enter value of b: "))
c = float(input("Enter value of c: "))

# Check if 'a' is zero
if a == 0:
    print("Not a quadratic equation!")
else:
    d = b**2 - 4*a*c   # Discriminant

    if d > 0:
        root1 = (-b + math.sqrt(d)) / (2*a)
        root2 = (-b - math.sqrt(d)) / (2*a)
        print("Roots are real and different:")
        print("Root 1 =", root1)
        print("Root 2 =", root2)

    elif d == 0:
        root = -b / (2*a)
        print("Roots are real and equal:")
        print("Root =", root)

    else:
        real = -b / (2*a)
        imag = math.sqrt(-d) / (2*a)
        print("Roots are complex:")
        print("Root 1 =", real, "+", imag, "i")
        print("Root 2 =", real, "-", imag, "i")

"""**4. Write a menu driven program to reverse the entered numbers and print the sum of digits entered.**"""

# Input number
num = int(input("Enter a number: "))

while True:
    print("\n--- MENU ---")
    print("1. Reverse the number")
    print("2. Sum of digits")
    print("3. Exit")

    choice = int(input("Enter your choice (1-3): "))

    if choice == 1:
        temp = num
        rev = 0
        while temp > 0:
            digit = temp % 10
            rev = rev * 10 + digit
            temp = temp // 10
        print("Reversed number:", rev)

    elif choice == 2:
        temp = num
        s = 0
        while temp > 0:
            digit = temp % 10
            s = s + digit
            temp = temp // 10
        print("Sum of digits:", s)

    elif choice == 3:
        print("Exiting program...")
        break

    else:
        print("Invalid choice! Try again.")

"""**5. Write a menu driven program to enter the number and print whether the number is odd or even prime.**"""

# Input number
num = int(input("Enter a number: "))

while True:
    print("\n--- MENU ---")
    print("1. Check Even or Odd")
    print("2. Check Prime")
    print("3. Exit")

    choice = int(input("Enter your choice (1-3): "))

    if choice == 1:
        if num % 2 == 0:
            print("Number is Even")
        else:
            print("Number is Odd")

    elif choice == 2:
        if num <= 1:
            print("Not a Prime number")
        else:
            is_prime = True
            for i in range(2, int(num**0.5) + 1):
                if num % i == 0:
                    is_prime = False
                    break

            if is_prime:
                print("Number is Prime")
            else:
                print("Number is Not Prime")

    elif choice == 3:
        print("Exiting program...")
        break

    else:
        print("Invalid choice! Try again.")

"""**6. Write a program to find maximum out of entered 3 numbers**"""

# Input three numbers
a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
c = float(input("Enter third number: "))

# Find maximum
if a >= b and a >= c:
    print("Maximum number is:", a)
elif b >= a and b >= c:
    print("Maximum number is:", b)
else:
    print("Maximum number is:", c)

"""**7. Write a program to display ASCII code of a character and vice versa.**"""

while True:
    print("\n--- MENU ---")
    print("1. Character to ASCII")
    print("2. ASCII to Character")
    print("3. Exit")

    choice = int(input("Enter your choice (1-3): "))

    if choice == 1:
        ch = input("Enter a character: ")
        print("ASCII value is:", ord(ch))

    elif choice == 2:
        num = int(input("Enter ASCII value: "))
        print("Character is:", chr(num))

    elif choice == 3:
        print("Exiting program...")
        break

    else:
        print("Invalid choice! Try again.")

"""**8. Write a program to check if the entered number is Armstrong or not.**"""

# Input number
num = int(input("Enter a number: "))

temp = num
n = len(str(num))   # number of digits
sum = 0

while temp > 0:
    digit = temp % 10
    sum = sum + digit**n
    temp = temp // 10

# Check condition
if sum == num:
    print("Armstrong number")
else:
    print("Not an Armstrong number")

"""**10. Write a program to enter the number of terms and to print the Fibonacci Series.**"""

# Input number of terms
n = int(input("Enter number of terms: "))

a = 0
b = 1

print("Fibonacci Series:")

for i in range(n):
    print(a, end=" ")
    c = a + b
    a = b
    b = c

"""**11. Write a program to enter the numbers and to print greatest number using loop.**"""

# Input how many numbers
n = int(input("Enter how many numbers: "))

# Take first number as maximum
max_num = float(input("Enter number 1: "))

# Loop for remaining numbers
for i in range(2, n + 1):
    num = float(input(f"Enter number {i}: "))
    if num > max_num:
        max_num = num

print("Greatest number is:", max_num)

"""**12. Write a program to enter the string and to check if it’s palindrome or not using loop.**"""

# Input string
s = input("Enter a string: ")

rev = ""

# Reverse using loop
for ch in s:
    rev = ch + rev

# Check palindrome
if s == rev:
    print("Palindrome")
else:
    print("Not a Palindrome")

"""**13. Write a program to enter the 5 subjects’ numbers and print the grades A/B/C/D/E.**"""

# Input marks for 5 subjects
total = 0

for i in range(1, 6):
    marks = float(input(f"Enter marks of subject {i}: "))
    total += marks

# Calculate percentage
percentage = total / 5

print("Percentage:", percentage)

# Assign grade
if percentage >= 90:
    print("Grade: A")
elif percentage >= 75:
    print("Grade: B")
elif percentage >= 60:
    print("Grade: C")
elif percentage >= 50:
    print("Grade: D")
else:
    print("Grade: E")

"""**14**"""

n = 5

for i in range(1, n + 1):
    # Print spaces
    for j in range(n - i):
        print("  ", end="")

    # Print numbers
    for k in range(n - i + 1, n + 1):
        print(k, end=" ")

    print()

"""**15**"""

def factorial(n):
    f = 1
    for i in range(1, n + 1):
        f *= i
    return f

def sin_series(x, n):
    result = 0

    for i in range(n):
        term = ((-1)**i) * (x**(2*i + 1)) / factorial(2*i + 1)
        result += term

    return result

# Input
x = float(input("Enter value of x (in radians): "))
n = int(input("Enter number of terms: "))

# Output
print("sin(x) =", sin_series(x, n))

"""**16. Write a program to determine EOQ using various inventory models.**"""

import math

print("\n--- Inventory Models ---")
print("1. Basic EOQ")
print("2. EOQ with Shortage")
print("3. Production EOQ (EPQ)")

choice = int(input("Enter your choice: "))

if choice == 1:
    D = float(input("Enter demand (D): "))
    S = float(input("Enter ordering cost (S): "))
    H = float(input("Enter holding cost (H): "))

    eoq = math.sqrt((2 * D * S) / H)
    print("EOQ =", eoq)

elif choice == 2:
    D = float(input("Enter demand (D): "))
    S = float(input("Enter ordering cost (S): "))
    H = float(input("Enter holding cost (H): "))
    P = float(input("Enter shortage cost (P): "))

    eoq = math.sqrt((2 * D * S / H) * ((H + P) / P))
    print("EOQ with shortage =", eoq)

elif choice == 3:
    D = float(input("Enter demand (D): "))
    S = float(input("Enter setup cost (S): "))
    H = float(input("Enter holding cost (H): "))
    p = float(input("Enter production rate (p): "))
    d = float(input("Enter demand rate (d): "))

    if p <= d:
        print("Error: Production rate must be greater than demand rate")
    else:
        epq = math.sqrt((2 * D * S / H) * (p / (p - d)))
        print("Production EOQ (EPQ) =", epq)

else:
    print("Invalid choice")

"""**17. Write a program to determine different characteristics using various queuing models.**"""

import math

def factorial(n):
    f = 1
    for i in range(1, n+1):
        f *= i
    return f

print("\n--- Queue Models ---")
print("1. M/M/1")
print("2. M/M/C")
print("3. M/M/1/K")

choice = int(input("Enter your choice: "))

# ---------------- M/M/1 ----------------
if choice == 1:
    lam = float(input("Enter λ: "))
    mu = float(input("Enter μ: "))

    if lam >= mu:
        print("System unstable")
    else:
        rho = lam / mu
        L = lam / (mu - lam)
        Lq = (lam**2) / (mu * (mu - lam))
        W = 1 / (mu - lam)
        Wq = lam / (mu * (mu - lam))

        print("ρ =", rho)
        print("L =", L)
        print("Lq =", Lq)
        print("W =", W)
        print("Wq =", Wq)

# ---------------- M/M/C ----------------
elif choice == 2:
    lam = float(input("Enter λ: "))
    mu = float(input("Enter μ: "))
    c = int(input("Enter number of servers (c): "))

    rho = lam / (c * mu)

    if rho >= 1:
        print("System unstable")
    else:
        sum1 = 0
        for n in range(c):
            sum1 += (lam/mu)**n / factorial(n)

        last = ((lam/mu)**c) / (factorial(c) * (1 - rho))
        P0 = 1 / (sum1 + last)

        Lq = (P0 * (lam/mu)**c * rho) / (factorial(c) * (1 - rho)**2)
        L = Lq + lam/mu
        W = L / lam
        Wq = Lq / lam

        print("ρ =", rho)
        print("L =", L)
        print("Lq =", Lq)
        print("W =", W)
        print("Wq =", Wq)

# ---------------- M/M/1/K ----------------
elif choice == 3:
    lam = float(input("Enter λ: "))
    mu = float(input("Enter μ: "))
    K = int(input("Enter system capacity (K): "))

    rho = lam / mu

    if rho == 1:
        P0 = 1 / (K + 1)
    else:
        P0 = (1 - rho) / (1 - rho**(K+1))

    L = 0
    for n in range(K+1):
        Pn = (rho**n) * P0
        L += n * Pn

    lam_eff = lam * (1 - (rho**K * P0))  # effective arrival rate
    W = L / lam_eff
    Wq = W - 1/mu
    Lq = lam_eff * Wq

    print("ρ =", rho)
    print("L =", L)
    print("Lq =", Lq)
    print("W =", W)
    print("Wq =", Wq)

else:
    print("Invalid choice")

"""**18. Write a program to implement Inheritance. Create a class Employee inherit two classes Manager and Clerk from Employee.**"""

# Base class
class Employee:
    def __init__(self, name, emp_id, salary):
        self.name = name
        self.emp_id = emp_id
        self.salary = salary

    def display(self):
        print("Name:", self.name)
        print("Employee ID:", self.emp_id)
        print("Salary:", self.salary)


# Derived class: Manager
class Manager(Employee):
    def __init__(self, name, emp_id, salary, bonus):
        super().__init__(name, emp_id, salary)
        self.bonus = bonus

    def total_salary(self):
        total = self.salary + self.bonus
        print("Manager Total Salary:", total)


# Derived class: Clerk
class Clerk(Employee):
    def __init__(self, name, emp_id, salary, overtime):
        super().__init__(name, emp_id, salary)
        self.overtime = overtime

    def total_salary(self):
        total = self.salary + self.overtime
        print("Clerk Total Salary:", total)


# Creating objects
print("\n--- Manager Details ---")
m = Manager("Vinay", 101, 50000, 10000)
m.display()
m.total_salary()

print("\n--- Clerk Details ---")
c = Clerk("Rahul", 102, 20000, 3000)
c.display()
c.total_salary()

"""# **19. Write a program to fit Poisson distribution on a given data.**"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import poisson
from scipy.optimize import minimize
import scipy.stats

np.random.seed(42)
data = np.random.poisson(lam=4.5, size=500)
print("Sample data (first 10):", data[:10])
print(f"Data range: {data.min()} to {data.max()}")
print(f"Total observations : {len(data)}")
print(f"Mean : {np.mean(data):.2f}")
print(f"Median : {np.median(data):.2f}")
print(f"Variance : {np.var(data):.2f}")


lamda_mle = np.mean(data)
print(f'Fitted lamda : {lamda_mle}')
print(f"True λ used    : 4.5  ← should be close!")

from scipy.stats import chisquare
values, observed = np.unique(data, return_counts=True)
expected = poisson.pmf(values, mu=lamda_mle) * len(data)
mask = expected >= 5

if not all(mask):
    print("\nNote: Some tail bins merged (expected count < 5)")

expected_f = expected[mask]
observed_f = observed[mask]
expected_f = expected_f * (observed_f.sum() / expected_f.sum())
chi2_stat, p_value = chisquare(f_obs=observed_f, f_exp=expected_f)
print(f"Chi-Square Statistic : {chi2_stat:.4f}")
print(f"P-value              : {p_value:.4f}")
print("Result:", "✅ Good fit (fail to reject H0)" if p_value > 0.05
                 else "❌ Poor fit (reject H0)")

x = np.arange(0, data.max() + 1)
fitted_probs = poisson.pmf(x, mu=lamda_mle)



plt.figure(figsize=(10, 5))
plt.bar(x - 0.2, np.bincount(data) / len(data),
        width=0.4, label="Observed (normalized)", color="steelblue", alpha=0.8)
plt.bar(x + 0.2, fitted_probs,
        width=0.4, label=f"Fitted Poisson (λ={lamda_mle:.2f})",
        color="orange", alpha=0.8)
plt.xlabel("Count (k)")
plt.ylabel("Probability")
plt.title("Observed Data vs Fitted Poisson Distribution")
plt.legend()
plt.tight_layout()
plt.savefig("poisson_fit.png", dpi=150)
plt.show()
print("\nPlot saved as poisson_fit.png")

"""# **20. Write a program to implement linear regression using python.**"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

np.random.seed(42)
hours   = np.random.uniform(1, 10, 100)               # 100 students, 1–10 hrs
marks   = 5 * hours + 10 + np.random.normal(0, 5, 100)

X = hours.reshape(-1, 1)   # shape: (100, 1)
y = marks

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(f"Training samples : {len(X_train)}")
print(f"Testing  samples : {len(X_test)}")

model = LinearRegression()
model.fit(X_train, y_train)

print(f"\nSlope     (m) : {model.coef_[0]:.4f}")
print(f"Intercept (c) : {model.intercept_:.4f}")
print(f"Equation      : y = {model.coef_[0]:.2f}x + {model.intercept_:.2f}")

y_pred = model.predict(X_test)

print("\nSample Predictions:")
print(f"{'Actual':>10}  {'Predicted':>10}")
for actual, predicted in zip(y_test[:5], y_pred[:5]):
    print(f"{actual:>10.2f}  {predicted:>10.2f}")

mse  = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2   = r2_score(y_test, y_pred)

print(f"\nMSE  (Mean Squared Error)       : {mse:.4f}")
print(f"RMSE (Root Mean Squared Error)  : {rmse:.4f}")
print(f"R²   (R-Squared Score)          : {r2:.4f}")
print("(R² closer to 1.0 = better fit)")

plt.figure(figsize=(10, 5))

# Scatter: actual data points
plt.scatter(X_test, y_test, color="steelblue", label="Actual data", alpha=0.7)

# Line: regression line
x_line = np.linspace(X.min(), X.max(), 100).reshape(-1, 1)
y_line = model.predict(x_line)
plt.plot(x_line, y_line, color="red", linewidth=2,
         label=f"Regression line: y = {model.coef_[0]:.2f}x + {model.intercept_:.2f}")

plt.xlabel("Hours Studied")
plt.ylabel("Marks Scored")
plt.title("Linear Regression — Hours vs Marks")
plt.legend()
plt.tight_layout()
plt.savefig("linear_regression.png", dpi=150)
plt.show()
print("Plot saved as linear_regression.png")

"""# **21. Write a program to perform read and write operation with .csv file.**"""

import pandas as pd

df = pd.read_csv("data1.csv")
print(df)

print(df.head())           # first 5 rows
print(df.shape)            # rows and columns
print(df.columns)          # column names
print(df.dtypes)

df.loc[df["Name "] == "Tanya", "Salary"] = 75000

# Delete a row
df = df[df["Name "] != "Bhavya"]

# Save back
df.to_csv("data1.csv", index=False)

print(df.head())

"""# **22. Write a program to enter multiple values-based data in multiple columns/rows and show that data in Python using DataFrames and pandas.**"""

import pandas as pd

data = {
    "Name"       : ["Alice", "Bob", "Charlie", "Diana", "Eve"],
    "Age"        : [25, 30, 22, 35, 28],
    "City"       : ["New York", "London", "Paris", "Tokyo", "Dubai"],
    "Salary"     : [55000, 62000, 48000, 71000, 59000],
    "Department" : ["HR", "IT", "Finance", "IT", "HR"]
}

df = pd.DataFrame(data)
print(df)
print("\n")
print(f'Shape of the DataFrame = {df.shape}')
print("\n")
print(df.columns)
print("\n")
print(df.dtypes)
print("\n")
print(df.describe)
print("\n")
print(df.head(3))
print("\n")
print(df.iloc[2])

print("\n")
print(df['Name'])

new_row = {
    "Name"       : "Frank",
    "Age"        : 32,
    "City"       : "Berlin",
    "Salary"     : 67000,
    "Department" : "Finance",
    "Bonus"      : 6700,
    "Senior"     : True
}

df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
print(df)

print("\n─── Average Salary by Department ───")
print(df.groupby("Department")["Salary"].mean())

print("\n─── Count of Employees per Department ───")
print(df.groupby("Department")["Name"].count())

print("\n─── Max Salary per Department ───")
print(df.groupby("Department")["Salary"].max())

"""# **23. Write a program in python to perform various statistical measures using pandas.**"""

import pandas as pd

# Create dataset
data = {
    "Marks": [45, 67, 78, 89, 56, 72, 60]
}

df = pd.DataFrame(data)

# Statistical Measures
print("Data:\n", df)

print("\nMean:", df["Marks"].mean())
print("Median:", df["Marks"].median())
print("Mode:\n", df["Marks"].mode())

print("Minimum:", df["Marks"].min())
print("Maximum:", df["Marks"].max())

print("Standard Deviation:", df["Marks"].std())
print("Variance:", df["Marks"].var())

print("Sum:", df["Marks"].sum())
print("Count:", df["Marks"].count())


print("\nSummary Statistics:\n", df.describe())

"""# **24. Write a program to plot a bar chart in python to display the result of a school for five consecutive years.**"""

import matplotlib.pyplot as plt

# Data
years  = [2020, 2021, 2022, 2023, 2024]
result = [78, 85, 82, 90, 88]       # pass percentage

# Plot
plt.bar(years, result, color="steelblue", width=0.5)

# Labels
plt.title("School Results for 5 Consecutive Years")
plt.xlabel("Year")
plt.ylabel("Pass Percentage (%)")

# Show value on top of each bar
for i, val in enumerate(result):
    plt.text(years[i], val + 0.5, f"{val}%", ha="center")

plt.tight_layout()
plt.show()

"""# **25. Write a program in python to plot a graph for the function y = x2**"""

import matplotlib.pyplot as plt
import numpy as np

# Data
x = np.linspace(-10, 10, 100)    # 100 points from -10 to 10
y = x ** 2                        # y = x²

# Plot
plt.plot(x, y, color="steelblue", linewidth=2)

# Labels
plt.title("Graph of y = x²")
plt.xlabel("x")
plt.ylabel("y = x²")

# Add grid and zero lines
plt.axhline(0, color="black", linewidth=0.8)   # horizontal line at y=0
plt.axvline(0, color="black", linewidth=0.8)   # vertical line at x=0
plt.grid(True, linestyle="--", alpha=0.6)

plt.tight_layout()
plt.show()

"""# **26. Write programs related to creating and modifying List, Tuple and Dictionary.**"""

empty_list = []
numbers = [1, 2, 3]
mixed = [1, "hello", 3.14]

# Modifying lists
numbers.append(4)
numbers.insert(1, 10)
numbers.remove(10)
numbers[0] = 100
numbers.extend([5, 6])
print(numbers)

my_tuple = (1, 2, 3, 4)
print("Original Tuple:", my_tuple)


# Convert to list
temp = list(my_tuple)

# Modify
temp.append(5)
temp[1] = 10

# Convert back to tuple
my_tuple = tuple(temp)

print("Modified Tuple:", my_tuple)

my_dict = {
    "name": "Vinay",
    "age": 22,
    "course": "CS"
}
print("Original Dictionary:", my_dict)


# Add new key-value
my_dict["city"] = "Delhi"

# Update value
my_dict["age"] = 23

# Remove element
my_dict.pop("course")

print("Modified Dictionary:", my_dict)

"""# **27. Write programs to find correlation between dependent and independent variables.**"""

import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])

r = np.corrcoef(x, y)[0, 1]

print("Correlation coefficient:", r)

"""# **28. Write programs for data visualization (Charts using plot() function, Pie Chart, Scatter Plot, Histogram, Bar Chart).**"""

import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [10, 20, 15, 25, 30]

plt.plot(x, y)
plt.title("Line Chart")
plt.xlabel("X-axis")
plt.ylabel("Y-axis")

plt.show()

import matplotlib.pyplot as plt

labels = ['A', 'B', 'C', 'D']
sizes = [30, 20, 25, 25]

plt.pie(sizes, labels=labels, autopct='%1.1f%%')
plt.title("Pie Chart")

plt.show()

import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [2, 4, 5, 4, 5]

plt.scatter(x, y)
plt.title("Scatter Plot")
plt.xlabel("X-axis")
plt.ylabel("Y-axis")

plt.show()

import matplotlib.pyplot as plt

data = [10, 20, 20, 30, 30, 30, 40, 50]

plt.hist(data, bins=5)
plt.title("Histogram")
plt.xlabel("Value")
plt.ylabel("Frequency")

plt.show()

import matplotlib.pyplot as plt

categories = ['A', 'B', 'C', 'D']
values = [10, 20, 15, 25]

plt.bar(categories, values)
plt.title("Bar Chart")
plt.xlabel("Categories")
plt.ylabel("Values")

plt.show()

"""# **29. Write programs making use of Pulp library.**"""

from pulp import *

# Create problem
model = LpProblem("Maximize_Profit", LpMaximize)

# Decision variables
x = LpVariable('x', lowBound=0)
y = LpVariable('y', lowBound=0)

# Objective function
model += 3*x + 2*y

# Constraints
model += x + y <= 4
model += x <= 2
model += y <= 3

# Solve
model.solve()

# Output
print("Status:", LpStatus[model.status])
print("x =", x.value())
print("y =", y.value())
print("Max Profit =", value(model.objective))

"""# **30. Write programs making use of Scipy.**:"""

from scipy import integrate

# Define function
def f(x):
    return x**2

# Integration
result, error = integrate.quad(f, 0, 2)

print("Result:", result)

import numpy as np
from scipy import linalg

A = np.array([[2, 1],
              [1, 3]])

B = np.array([5, 6])

solution = linalg.solve(A, B)

print("Solution:", solution)

"""**23-04-2026**"""

import seaborn as sns

tips=sns.load_dataset("tips")

sns.lineplot(x='total_bill',y='tip' , data=tips)

sns.scatterplot(x='total_bill',y='tip' , data=tips)

sns.regplot(x='total_bill',y='tip' , data=tips)

sns.relplot(x='total_bill',y='tip' , data=tips)

sns.boxplot(x='total_bill',y='tip' , data=tips)

sns.load_dataset("dots")

dots=sns.load_dataset("dots")

sns.lineplot(x='time',y='firing_rate' , data=dots)

sns.scatterplot(x='time',y='firing_rate' , data=dots)

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Given data
data = {
    'TV': [230.1, 44.5, 17.2, 151.5, 180.8],
    'Radio': [37.8, 39.3, 45.9, 41.3, 10.8],
    'Newspaper': [69.2, 45.1, 69.3, 58.5, 58.4],
    'Sales': [22.1, 10.4, 9.3, 18.5, 12.9]
}

df = pd.DataFrame(data)

# Take TV as independent variable (X) and Sales as dependent variable (y)
X = df[['TV']]
y = df['Sales']

# Train Linear Regression model
model = LinearRegression()
model.fit(X, y)

# Predict regression line
X_line = pd.DataFrame({'TV': [df['TV'].min(), df['TV'].max()]})
y_line = model.predict(X_line)

# Plot graph
plt.figure(figsize=(8,5))
plt.scatter(X, y, color='red', s=70, label='points (TV, Sales)')
plt.plot(X_line, y_line, color='skyblue', linewidth=2, label='line of best fit')

# Labels and title
plt.title("Regression Line")
plt.xlabel("TV Advertising")
plt.ylabel("Sales")
plt.legend()

plt.show()